# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='istakip',
            name='başlangıç_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='istakip',
            name='durum_güncelleme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='istakip',
            name='durumu',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='istakip',
            name='oluşturma_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='istakip',
            name='sonlanma_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
