# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0002_auto_20170920_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istakip',
            name='durumu',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
